# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
    vba_image:
        type: string
        default: knknkn1162/vba_extractor

jobs:
    build:
        machine: true
        steps:
            - run:
                name: docker login
                command: |
                    echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
            - checkout
            - run:
                name: docker build
                command: |
                    docker build -t << pipeline.parameters.vba_image >> .
            - run:
                name: docker push
                command: |
                    docker push << pipeline.parameters.vba_image >>
workflows:
    build:
        jobs:
            - build:
                context:
                    - dockerhub
